# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CGiTktHC-2swm0LTMyBVvaNnvt8QU-Cs
"""

import nltk
#nltk.download('punkt')
#nltk.download('punkt-tab')
nltk.download()

import streamlit as st
from transformers import pipeline
import pdfplumber
import nltk

# Download 'punkt' resource if not already present
try:
    nltk.data.find('tokenizers/punkt')
except LookupError:
    nltk.download('punkt')

from nltk.tokenize import sent_tokenize

# Improved text chunking
def split_into_chunks(text, max_chunk_size):
    sentences = sent_tokenize(text)
    chunks, current_chunk = [], []
    current_length = 0

    for sentence in sentences:
        sentence_length = len(sentence)
        if current_length + sentence_length > max_chunk_size:
            chunks.append(" ".join(current_chunk))
            current_chunk, current_length = [], 0
        current_chunk.append(sentence)
        current_length += sentence_length

    if current_chunk:
        chunks.append(" ".join(current_chunk))
    return chunks

# App title
st.title("PDF Summarizer")

# File upload
uploaded_file = st.file_uploader("uploadfile", type="pdf")

if uploaded_file:
    try:
        # Extract text from PDF
        with pdfplumber.open(uploaded_file) as pdf:
            text = ''.join([page.extract_text() or "" for page in pdf.pages])  # Handle NoneType

        # Check if the extracted text is valid and not empty
        if not text.strip():
            st.error("The uploaded PDF contains no extractable text.")
        else:
            # Display the length of the extracted text
            text_length = len(text)
            st.write(f"Total text length: {text_length} characters")

            # Summarizer pipeline
            summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

            # Split text into chunks
            max_chunk_size = 500
            text_chunks = split_into_chunks(text, max_chunk_size)

            # Summarize each chunk
            summary = []
            for chunk in text_chunks:
                input_length = len(chunk.split())
                max_length = min(150, max(input_length // 2, 20))
                min_length = max(10, max_length // 3)

                summarized_chunk = summarizer(chunk, max_length=max_length, min_length=min_length, do_sample=False)
                summary.append(summarized_chunk[0]['summary_text'])

            # Combine and display the summary
            st.subheader("Summary")
            st.write(" ".join(summary))
    except Exception as e:
        st.error(f"An error occurred: {e}")
else:
    st.info("Please upload a PDF file to get started.")

if __name__ == "__main__":
    main()

#!streamlit run pdf.main.streamlit_app.py

#!pip install pyngrok --quiet

#from pyngrok import ngrok

'''
import streamlit as st
from transformers import pipeline
import pdfplumber
import nltk

# Download 'punkt' resource if not already present
try:
    nltk.data.find('tokenizers/punkt')
except LookupError:
    nltk.download('punkt')

from nltk.tokenize import sent_tokenize

# Improved text chunking
def split_into_chunks(text, max_chunk_size):
    sentences = sent_tokenize(text)
    chunks, current_chunk = [], []
    current_length = 0

    for sentence in sentences:
        sentence_length = len(sentence)
        if current_length + sentence_length > max_chunk_size:
            chunks.append(" ".join(current_chunk))
            current_chunk, current_length = [], 0
        current_chunk.append(sentence)
        current_length += sentence_length

    if current_chunk:
        chunks.append(" ".join(current_chunk))
    return chunks

# App title
st.title("PDF Summarizer")

# File upload
# Replace "YOUR_AUTHTOKEN" with your actual authtoken
ngrok.set_auth_token("2r5ceh99DvuPp9E1msTW1QQVY78_2gLy9nYpjgZWcjCMyL8G2")

# Rest of your code...
!nohup streamlit run /content/Computational_Intelligence (2).py &
url = ngrok.connect(8501)
print(url)

if uploaded_file:
    try:
        # Extract text from PDF
        with pdfplumber.open(uploaded_file) as pdf:
            text = ''.join([page.extract_text() or "" for page in pdf.pages])  # Handle NoneType

        if not text.strip():
            st.error("The uploaded PDF contains no extractable text.")
        else:
            # Summarizer pipeline
            summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

            # Split text into chunks using the defined function
            max_chunk_size = 500
            text_chunks = split_into_chunks(text, max_chunk_size)  # Call the function here

            # Summarize each chunk
            summary = []
            for chunk in text_chunks:
                input_length = len(chunk.split())
                max_length = min(150, max(input_length // 2, 20))
                min_length = max(10, max_length // 3)

                summarized_chunk = summarizer(chunk, max_length=max_length, min_length=min_length, do_sample=False)
                summary.append(summarized_chunk[0]['summary_text'])

            # Combine and display the summary
            st.subheader("Summary")
            st.write(" ".join(summary))
    except Exception as e:
        st.error(f"An error occurred: {e}")
else:
    st.info("Please upload a PDF file to get started.")

'''
